### ISSUE TITLE
FastStringUtils.split

### ISSUE THREAD

**Issue by mnalmahmud** [Konloch/FastStringUtils#1]
Hello!
I hope you are doing fine.

FastStringUtils.split("A:B::C", ":")
Expected -> ["A", "B", "", "C"] // As per java.lang.String.split behavior
Actual -> ["A", "B", "C"] // Bugg-ish output i guess or expected?

**Comment by Konloch** [comment]
Hey, thanks for taking an interest in this project! The goal is to mirror the behavior of String.split so I will fix this, thank you for the report!

**Comment by mnalmahmud** [comment]
My pleasure, hoping you will resolve this as soon as possible.

**Comment by Konloch** [comment]
This isn't fully fixed, multi-character searches still return the buggish output but single character searches are fixed, I am still working on the mutli-character searching.

Thank you again for this report!

**Comment by mnalmahmud** [comment]
Okay! Thanks for the half-fix. Kindly, let me know whenever this bug is fully smashed. Thanks again for the awesome job!
